var drugs = [
	"Abiraterone Acetate",
	"Abraxane",
	"Abitrexate",
	"Adcetris",
	"Adrucil",
	"Adriamycin",
	"Afinitor",
	"Aldara",
	"Aldesleukin",
	"Alemtuzumab",
	"Alimta",
	"Aloxi",
	"Ambochlorin",
	"Amboclorin",
	"Aminolevulinic Acid",
	"Anastrozole",
	"Aprepitant",
	"Arranon",
	"Aromasin",
	"Arimidex",
	"Arsenic Trioxide",
	"Arzerra",
	"Asparaginase Erwinia chrysanthemi",
	"Axitinib",
	"Avastin",
	"Azacitidine",
	"Bendamustine Hydrochloride",
	"Bexarotene",
	"Bevacizumab",
	"Bortezomib",
	"Bleomycin",
	"Bexxar",
	"Bosutinib",
	"Brentuximab Vedotin",
	"Bosulif",
	"Cabazitaxel",
	"Camptosar",
	"Campath",
	"Capecitabine",
	"Carboplatin",
	"Carfilzomib",
	"CeeNU",
	"Cerubidine",
	"Cervarix",
	"Cetuximab",
	"Chlorambucil",
	"Cisplatin",
	"Clafen",
	"Clofarabine",
	"Clofarex",
	"Clolar",
	"Crizotinib",
	"Cosmegen",
	"Cyfos",
	"Cytarabine",
	"Cyclophosphamide",
	"Cytarabine Liposomal",
	"Dacarbazine",
	"Cytoxan",
	"Cytosar-U",
	"Dasatinib",
	"Dacogen",
	"Dactinomycin",
	"Degarelix",
	"Daunorubicin Hydrochloride",
	"Decitabine",
	"DepoCyt",
	"Denosumab",
	"Denileukin Diftitox",
	"DepoFoam",
	"Docetaxel",
	"Dexrazoxane Hydrochloride",
	"Doxil",
	"Doxorubicin Hydrochloride",
	"Doxorubicin Hydrochloride Liposome",
	"Dox-SL",
	"DTIC-Dome",
	"Efudex",
	"Elitek",
	"Ellence",
	"Eloxatin",
	"Eltrombopag Olamine",
	"Emend",
	"Enzalutamide",
	"Erbitux",
	"Epirubicin Hydrochloride",
	"Eribulin Mesylate",
	"Erivedge",
	"Erlotinib Hydrochloride",
	"Erwinaze",
	"Etopophos",
	"Etoposide",
	"Etoposide Phosphate",
	"Evacet",
	"Everolimus",
	"Evista",
	"Exemestane",
	"Fareston",
	"Faslodex",
	"Femara",
	"Fludara",
	"Filgrastim",
	"Fludarabine Phosphate",
	"Fluoroplex",
	"Fluorouracil",
	"Folex PFS",
	"Folex",
	"Folotyn",
	"Fulvestrant",
	"Gardasil",
	"Gefitinib",
	"Gemcitabine Hydrochloride",
	"Gemzar",
	"Gemtuzumab Ozogamicin",
	"Gleevec",
	"Glucarpidase",
	"Herceptin",
	"Halaven",
	"HPV Bivalent Vaccine Recombinant",
	"HPV Quadrivalent Vaccine Recombinant",
	"Hycamtin",
	"Ibritumomab Tiuxetan",
	"Ifosfamide",
	"Ifosfamidum",
	"Ifex",
	"Inlyta",
	"Imiquimod",
	"Imatinib Mesylate",
	"Ipilimumab",
	"Iressa",
	"Irinotecan Hydrochloride",
	"Istodax",
	"Ixabepilone",
	"Jakafi",
	"Ixempra",
	"Kepivance",
	"Jevtana",
	"Kyprolis",
	"Keoxifene",
	"Lapatinib Ditosylate",
	"Letrozole",
	"Lenalidomide",
	"Leucovorin Calcium",
	"Leukeran",
	"Leuprolide Acetate",
	"Levulan",
	"Linfolizin",
	"LipoDox",
	"Liposomal Cytarabine",
	"Lupron",
	"Lomustine",
	"Lupron Depot",
	"Lupron Depot-Ped",
	"Lupron Depot-3 Month",
	"Lupron Depot-4 Month",
	"Marqibo",
	"Mechlorethamine Hydrochloride",
	"Matulane",
	"Mesna",
	"Mesnex",
	"Methotrexate",
	"Methazolastone",
	"Mexate",
	"Methotrexate LPF",
	"Mitomycin C",
	"Mexate-AQ",
	"Mitozytrex",
	"Mozobil",
	"Mustargen",
	"Mutamycin",
	"Mylosar",
	"Mylotarg",
	"Nanoparticle Paclitaxel",
	"Nelarabine",
	"Navelbine",
	"Neosar",
	"Neupogen",
	"Nilotinib",
	"Nolvadex",
	"Ofatumumab",
	"Nplate",
	"Nexavar",
	"Omacetaxine Mepesuccinate",
	"Oncaspar",
	"Oxaliplatin",
	"Paclitaxel Albumin-stabilized Nanoparticle Formulation",
	"Palifermin",
	"Palonosetron Hydrochloride",
	"Ontak",
	"Paclitaxel",
	"Paraplat",
	"Panitumumab",
	"Pegaspargase",
	"Pazopanib Hydrochloride",
	"Paraplatin",
	"Pemetrexed Disodium",
	"Perjeta",
	"Pertuzumab",
	"Platinol",
	"Platinol-AQ",
	"Plerixafor",
	"Pralatrexate",
	"Prednisone",
	"Procarbazine Hydrochloride",
	"Proleukin",
	"Promacta",
	"Prolia",
	"Provenge",
	"Rasburicase",
	"Raloxifene Hydrochloride",
	"Recombinant HPV Bivalent Vaccine",
	"Recombinant HPV Quadrivalent Vaccine",
	"Regorafenib",
	"Revlimid",
	"Rituxan",
	"Rheumatrex",
	"Rituximab",
	"Romiplostim",
	"Romidepsin",
	"Rubidomycin",
	"Ruxolitinib Phosphate",
	"Sclerosol Intrapleural Aerosol",
	"Sorafenib Tosylate",
	"Sipuleucel-T",
	"Sprycel",
	"Sterile Talc Powder",
	"Steritalc",
	"Sunitinib Malate",
	"Stivarga",
	"Sutent",
	"Synovir",
	"Synribo",
	"Talc",
	"Tamoxifen Citrate",
	"Tarabine PFS",
	"Tarceva",
	"Targretin",
	"Tasigna",
	"Taxol",
	"Temozolomide",
	"Taxotere",
	"Temodar",
	"Temsirolimus",
	"Thalidomide",
	"Thalomid",
	"Topotecan Hydrochloride",
	"Toposar",
	"Toremifene",
	"Totect",
	"Torisel",
	"Tositumomab and I 131 Iodine Tositumomab",
	"Treanda",
	"Trastuzumab",
	"Tykerb",
	"Vandetanib",
	"Trisenox",
	"Vectibix",
	"Velban",
	"Velsar",
	"Velcade",
	"VePesid",
	"Vemurafenib",
	"Viadur",
	"Vinblastine Sulfate",
	"Vidaza",
	"Vincasar PFS",
	"Vincristine Sulfate",
	"Vincristine Sulfate Liposome",
	"Vinorelbine Tartrate",
	"Voraxaze",
	"Vismodegib",
	"Votrient",
	"Vorinostat",
	"Wellcovorin",
	"Xalkori",
	"Xeloda",
	"Xgeva",
	"Yervoy",
	"Xtandi",
	"Zelboraf",
	"Zaltrap",
	"Zevalin",
	"Zinecard",
	"Zoledronic Acid",
	"Ziv-Aflibercept",
	"Zometa",
	"Zytiga",
	"Zolinza"
];
