/*
 * CTD2 Dashboard API
 * API access to CTD2 Dashboard
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ocg@mail.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CentersSubmissions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-14T22:43:55.759Z")
public class InlineResponse200 {
  @SerializedName("center_name")
  private String centerName = null;

  @SerializedName("center_id")
  private String centerId = null;

  @SerializedName("principal_investigator")
  private String principalInvestigator = null;

  @SerializedName("submissions")
  private List<CentersSubmissions> submissions = null;

  public InlineResponse200 centerName(String centerName) {
    this.centerName = centerName;
    return this;
  }

   /**
   * Get centerName
   * @return centerName
  **/
  @ApiModelProperty(value = "")
  public String getCenterName() {
    return centerName;
  }

  public void setCenterName(String centerName) {
    this.centerName = centerName;
  }

  public InlineResponse200 centerId(String centerId) {
    this.centerId = centerId;
    return this;
  }

   /**
   * Get centerId
   * @return centerId
  **/
  @ApiModelProperty(value = "")
  public String getCenterId() {
    return centerId;
  }

  public void setCenterId(String centerId) {
    this.centerId = centerId;
  }

  public InlineResponse200 principalInvestigator(String principalInvestigator) {
    this.principalInvestigator = principalInvestigator;
    return this;
  }

   /**
   * Get principalInvestigator
   * @return principalInvestigator
  **/
  @ApiModelProperty(value = "")
  public String getPrincipalInvestigator() {
    return principalInvestigator;
  }

  public void setPrincipalInvestigator(String principalInvestigator) {
    this.principalInvestigator = principalInvestigator;
  }

  public InlineResponse200 submissions(List<CentersSubmissions> submissions) {
    this.submissions = submissions;
    return this;
  }

  public InlineResponse200 addSubmissionsItem(CentersSubmissions submissionsItem) {
    if (this.submissions == null) {
      this.submissions = new ArrayList<CentersSubmissions>();
    }
    this.submissions.add(submissionsItem);
    return this;
  }

   /**
   * Get submissions
   * @return submissions
  **/
  @ApiModelProperty(value = "")
  public List<CentersSubmissions> getSubmissions() {
    return submissions;
  }

  public void setSubmissions(List<CentersSubmissions> submissions) {
    this.submissions = submissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.centerName, inlineResponse200.centerName) &&
        Objects.equals(this.centerId, inlineResponse200.centerId) &&
        Objects.equals(this.principalInvestigator, inlineResponse200.principalInvestigator) &&
        Objects.equals(this.submissions, inlineResponse200.submissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(centerName, centerId, principalInvestigator, submissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    centerName: ").append(toIndentedString(centerName)).append("\n");
    sb.append("    centerId: ").append(toIndentedString(centerId)).append("\n");
    sb.append("    principalInvestigator: ").append(toIndentedString(principalInvestigator)).append("\n");
    sb.append("    submissions: ").append(toIndentedString(submissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

