/*
 * CTD2 Dashboard API
 * API access to CTD2 Dashboard
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ocg@mail.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Observation;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-14T22:43:55.759Z")
public class InlineResponse2001 {
  @SerializedName("submission_center")
  private String submissionCenter = null;

  @SerializedName("submission_name")
  private String submissionName = null;

  @SerializedName("submission_date")
  private LocalDate submissionDate = null;

  @SerializedName("tier")
  private Integer tier = null;

  @SerializedName("project")
  private String project = null;

  @SerializedName("submission_description")
  private String submissionDescription = null;

  @SerializedName("story_title")
  private String storyTitle = null;

  @SerializedName("observation_count")
  private Integer observationCount = null;

  @SerializedName("observations")
  private List<Observation> observations = null;

  public InlineResponse2001 submissionCenter(String submissionCenter) {
    this.submissionCenter = submissionCenter;
    return this;
  }

   /**
   * Get submissionCenter
   * @return submissionCenter
  **/
  @ApiModelProperty(value = "")
  public String getSubmissionCenter() {
    return submissionCenter;
  }

  public void setSubmissionCenter(String submissionCenter) {
    this.submissionCenter = submissionCenter;
  }

  public InlineResponse2001 submissionName(String submissionName) {
    this.submissionName = submissionName;
    return this;
  }

   /**
   * Get submissionName
   * @return submissionName
  **/
  @ApiModelProperty(value = "")
  public String getSubmissionName() {
    return submissionName;
  }

  public void setSubmissionName(String submissionName) {
    this.submissionName = submissionName;
  }

  public InlineResponse2001 submissionDate(LocalDate submissionDate) {
    this.submissionDate = submissionDate;
    return this;
  }

   /**
   * Get submissionDate
   * @return submissionDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getSubmissionDate() {
    return submissionDate;
  }

  public void setSubmissionDate(LocalDate submissionDate) {
    this.submissionDate = submissionDate;
  }

  public InlineResponse2001 tier(Integer tier) {
    this.tier = tier;
    return this;
  }

   /**
   * Get tier
   * minimum: 1
   * maximum: 3
   * @return tier
  **/
  @ApiModelProperty(value = "")
  public Integer getTier() {
    return tier;
  }

  public void setTier(Integer tier) {
    this.tier = tier;
  }

  public InlineResponse2001 project(String project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(value = "")
  public String getProject() {
    return project;
  }

  public void setProject(String project) {
    this.project = project;
  }

  public InlineResponse2001 submissionDescription(String submissionDescription) {
    this.submissionDescription = submissionDescription;
    return this;
  }

   /**
   * Get submissionDescription
   * @return submissionDescription
  **/
  @ApiModelProperty(value = "")
  public String getSubmissionDescription() {
    return submissionDescription;
  }

  public void setSubmissionDescription(String submissionDescription) {
    this.submissionDescription = submissionDescription;
  }

  public InlineResponse2001 storyTitle(String storyTitle) {
    this.storyTitle = storyTitle;
    return this;
  }

   /**
   * Get storyTitle
   * @return storyTitle
  **/
  @ApiModelProperty(value = "")
  public String getStoryTitle() {
    return storyTitle;
  }

  public void setStoryTitle(String storyTitle) {
    this.storyTitle = storyTitle;
  }

  public InlineResponse2001 observationCount(Integer observationCount) {
    this.observationCount = observationCount;
    return this;
  }

   /**
   * The total number of observations in a submission
   * @return observationCount
  **/
  @ApiModelProperty(value = "The total number of observations in a submission")
  public Integer getObservationCount() {
    return observationCount;
  }

  public void setObservationCount(Integer observationCount) {
    this.observationCount = observationCount;
  }

  public InlineResponse2001 observations(List<Observation> observations) {
    this.observations = observations;
    return this;
  }

  public InlineResponse2001 addObservationsItem(Observation observationsItem) {
    if (this.observations == null) {
      this.observations = new ArrayList<Observation>();
    }
    this.observations.add(observationsItem);
    return this;
  }

   /**
   * Get observations
   * @return observations
  **/
  @ApiModelProperty(value = "")
  public List<Observation> getObservations() {
    return observations;
  }

  public void setObservations(List<Observation> observations) {
    this.observations = observations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.submissionCenter, inlineResponse2001.submissionCenter) &&
        Objects.equals(this.submissionName, inlineResponse2001.submissionName) &&
        Objects.equals(this.submissionDate, inlineResponse2001.submissionDate) &&
        Objects.equals(this.tier, inlineResponse2001.tier) &&
        Objects.equals(this.project, inlineResponse2001.project) &&
        Objects.equals(this.submissionDescription, inlineResponse2001.submissionDescription) &&
        Objects.equals(this.storyTitle, inlineResponse2001.storyTitle) &&
        Objects.equals(this.observationCount, inlineResponse2001.observationCount) &&
        Objects.equals(this.observations, inlineResponse2001.observations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(submissionCenter, submissionName, submissionDate, tier, project, submissionDescription, storyTitle, observationCount, observations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    submissionCenter: ").append(toIndentedString(submissionCenter)).append("\n");
    sb.append("    submissionName: ").append(toIndentedString(submissionName)).append("\n");
    sb.append("    submissionDate: ").append(toIndentedString(submissionDate)).append("\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    submissionDescription: ").append(toIndentedString(submissionDescription)).append("\n");
    sb.append("    storyTitle: ").append(toIndentedString(storyTitle)).append("\n");
    sb.append("    observationCount: ").append(toIndentedString(observationCount)).append("\n");
    sb.append("    observations: ").append(toIndentedString(observations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

