/*
 * CTD2 Dashboard API
 * API access to CTD2 Dashboard
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ocg@mail.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SubjectXref;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ObservationSubjectList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-14T22:43:55.759Z")
public class ObservationSubjectList {
  @SerializedName("class")
  private String propertyClass = null;

  @SerializedName("role")
  private String role = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("synonyms")
  private List<String> synonyms = null;

  @SerializedName("xref")
  private List<SubjectXref> xref = null;

  public ObservationSubjectList propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Get propertyClass
   * @return propertyClass
  **/
  @ApiModelProperty(value = "")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public ObservationSubjectList role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public ObservationSubjectList description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ObservationSubjectList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ObservationSubjectList synonyms(List<String> synonyms) {
    this.synonyms = synonyms;
    return this;
  }

  public ObservationSubjectList addSynonymsItem(String synonymsItem) {
    if (this.synonyms == null) {
      this.synonyms = new ArrayList<String>();
    }
    this.synonyms.add(synonymsItem);
    return this;
  }

   /**
   * Get synonyms
   * @return synonyms
  **/
  @ApiModelProperty(value = "")
  public List<String> getSynonyms() {
    return synonyms;
  }

  public void setSynonyms(List<String> synonyms) {
    this.synonyms = synonyms;
  }

  public ObservationSubjectList xref(List<SubjectXref> xref) {
    this.xref = xref;
    return this;
  }

  public ObservationSubjectList addXrefItem(SubjectXref xrefItem) {
    if (this.xref == null) {
      this.xref = new ArrayList<SubjectXref>();
    }
    this.xref.add(xrefItem);
    return this;
  }

   /**
   * Get xref
   * @return xref
  **/
  @ApiModelProperty(value = "")
  public List<SubjectXref> getXref() {
    return xref;
  }

  public void setXref(List<SubjectXref> xref) {
    this.xref = xref;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObservationSubjectList observationSubjectList = (ObservationSubjectList) o;
    return Objects.equals(this.propertyClass, observationSubjectList.propertyClass) &&
        Objects.equals(this.role, observationSubjectList.role) &&
        Objects.equals(this.description, observationSubjectList.description) &&
        Objects.equals(this.name, observationSubjectList.name) &&
        Objects.equals(this.synonyms, observationSubjectList.synonyms) &&
        Objects.equals(this.xref, observationSubjectList.xref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyClass, role, description, name, synonyms, xref);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObservationSubjectList {\n");
    
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    synonyms: ").append(toIndentedString(synonyms)).append("\n");
    sb.append("    xref: ").append(toIndentedString(xref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

