/*
 * CTD2 Dashboard API
 * API access to CTD2 Dashboard
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ocg@mail.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * SubjectObservationCount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-14T22:43:55.759Z")
public class SubjectObservationCount {
  @SerializedName("tier1")
  private Integer tier1 = null;

  @SerializedName("tier2")
  private Integer tier2 = null;

  @SerializedName("tier3")
  private Integer tier3 = null;

  public SubjectObservationCount tier1(Integer tier1) {
    this.tier1 = tier1;
    return this;
  }

   /**
   * Get tier1
   * @return tier1
  **/
  @ApiModelProperty(value = "")
  public Integer getTier1() {
    return tier1;
  }

  public void setTier1(Integer tier1) {
    this.tier1 = tier1;
  }

  public SubjectObservationCount tier2(Integer tier2) {
    this.tier2 = tier2;
    return this;
  }

   /**
   * Get tier2
   * @return tier2
  **/
  @ApiModelProperty(value = "")
  public Integer getTier2() {
    return tier2;
  }

  public void setTier2(Integer tier2) {
    this.tier2 = tier2;
  }

  public SubjectObservationCount tier3(Integer tier3) {
    this.tier3 = tier3;
    return this;
  }

   /**
   * Get tier3
   * @return tier3
  **/
  @ApiModelProperty(value = "")
  public Integer getTier3() {
    return tier3;
  }

  public void setTier3(Integer tier3) {
    this.tier3 = tier3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectObservationCount subjectObservationCount = (SubjectObservationCount) o;
    return Objects.equals(this.tier1, subjectObservationCount.tier1) &&
        Objects.equals(this.tier2, subjectObservationCount.tier2) &&
        Objects.equals(this.tier3, subjectObservationCount.tier3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tier1, tier2, tier3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectObservationCount {\n");
    
    sb.append("    tier1: ").append(toIndentedString(tier1)).append("\n");
    sb.append("    tier2: ").append(toIndentedString(tier2)).append("\n");
    sb.append("    tier3: ").append(toIndentedString(tier3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

